
version: 2

models:
    - name: stg_athelete
      description: "A starter dbt model"
      columns:
          - name: Athelete_ID
            description: "primary key for athelete"
            tests:
                - unique
                - not_null
    - name: stg_coaches
      description: "coaches details"
      columns:
          - name: Coach_ID
            description: "efgh"
            tests:
                - not_null
                - unique
          - name: fellow_coaches
            description: "abcd"
            tests:
                - not_null
                - dbt_utils.expression_is_true:
                    expression: "fellow_coaches > 0"
